# stolen from https://github.com/facebook/chef-cookbooks/blob/main/.github/workflows/ci.yml
name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
jobs:
  # ruby:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       ruby: [2.5]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2
  #   - name: Setup Ruby
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: ${{ matrix.ruby }}
  #   - name: Install dependencies
  #     run: bundle install
  #   - name: Run rspec
  #     run: ./scripts/run_chefspec
  #   - name: Run rubocop
  #     run: ./scripts/run_rubocop .rubocop.yml
  #   - name: Run foodcritic
  #     run: ./scripts/run_foodcritic
  kitchen:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - centos-7
          # - centos-stream-8
          # - ubuntu-1804
          - ubuntu-2004
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install bundler
      run: gem install bundler
    - name: Install gems via bundler
      run: bundle install
    - name: Install Chef
      uses: actionshub/chef-install@1.1.0
      with:
        project: chef-workstation
        version: 20.11.180
    - name: Run Kitchen
      uses: actionshub/test-kitchen@2.0.0
      with:
        suite: linux
        os: ${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        CHEF_VERSION: 13.10.0
  # shellcheck:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Run Shellcheck
  #       uses: ludeeus/action-shellcheck@0.3.0

